
- name: install packages
  apt: 
    pkg:
      - python3-pip

- name: install python packages
  pip:
    name:
      - pip
      - virtualenv
    extra_args: --upgrade
    executable: pip3

- name: create site home folder
  file:
    path: '{{site_home }}'
    state: directory

- name: install python env packages
  pip:
    name: gunicorn
    virtualenv: '{{ virtualenv_home }}'
    virtualenv_python: python3
