---

- hosts: all
  gather_facts: false
#  connection: paramiko
  
  user: ubuntu
  become: true
  become_user: root
  
  roles:
    - apt-get
    - swap
    - python3-pip-virtualenv
    - certbot-nginx
    - tmpreaper
    - xlsform
